### ISSUE TITLE
"Controleer of huizen nog online zijn" reponse/page is empty

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#13]
not sure if this is the reason:

[Sat Jun 06 18:15:05.307819 2020] [:error] [pid 2682] [client xxx:48142] PHP Notice:  Undefined index: id in /xxx/funda/check_online.php on line 9, referer: http://xxx/funda/index.php

**Comment by physje** [comment]
Reden voor lege pagina komt door regel 22 en 24, script zoekt verkochte huizen die half jaar geleden voor het laatst gezien zijn.
Door regel 22 te wijzigen in `$halfJaar = mktime(0,0,0,date("n"), date("j")-1, date("Y"));` zoekt hij naar huizen die een dag geleden voor het laatst gezien zijn. Dan zal je denk ik geen lege pagina meer zien.

PHP Notice voor regel 9 is ook opgelost. Gaat mee in een van de volgende commits

**Comment by physje** [comment]
Bovengenoemde commit over r9 heeft 30 juni 2020 plaats gevonden ([cfb856e](https://github.com/physje/funda/commit/cfb856ec2a813027277e151d3fd9d0b5ea237936#diff-e7700cf30433390156fbb58c9b6e9c362733dce6fdbd8decd98d571fcbc4fc8e))
