### ISSUE TITLE
database updates

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#14]
Hoi,

Zag dat je wat database updates hebt doorgevoerd tussen tabel_14-08-2019.sql en tabel_06-06-2020.sql.

Kijk ik over een upgrade pad heen?

Voor nu even handmatig gedaan; (myisam naar innodb even gelaten)

```
ALTER TABLE funda_resultaat CHANGE ` nieuw` `nieuw` set('0','1') NOT NULL DEFAULT '1';

CREATE TABLE `funda_wijken` (
  `id` int(6) NOT NULL,
  `active` set('0','1') NOT NULL DEFAULT '1',
  `naam_leesbaar` text NOT NULL,
  `naam_funda` text NOT NULL,
  `stad` text NOT NULL,
  `last_checked` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `funda_wijken` ADD PRIMARY KEY (`id`);
ALTER TABLE `funda_wijken` MODIFY `id` int(3) NOT NULL AUTO_INCREMENT;
```

Gr

**Comment by physje** [comment]
onderhoud/onderhoud_2019-11-25.php doet dat als het goed is.
Bij volgende commit wordt de datum-notatie van .sql en .php-files ook gelijk getrokken.

**Comment by jalbstmeijer** [comment]
Als die laatst aangekondigde commit gedaan is kan deze volgens mij ook wel dicht

**Comment by physje** [comment]
Is 30 juni 2020 gebeurd ([cfb856e](https://github.com/physje/funda/commit/cfb856ec2a813027277e151d3fd9d0b5ea237936))
