### ISSUE TITLE
Undefined variable voor cron funda/check.php

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#15]
Hoi,

Bij runnen van de funda/check.php cron zie ik:

PHP Notice: Undefined variable: letter in funda/include/functions.php on line 438
PHP Notice:  Undefined variable: toevoeging in funda/include/functions.php on line 439

Geen idee wat de impact hiervan is.

Gr,

**Comment by jalbstmeijer** [comment]
Er wordt nergens gesproken over php versies.
Eerst getest met php-54 en toen php-74.
De error zie je vaak bij  gebruik van globals.
Heb fit met een workaround pogen op te lossen zoals beschreven in https://stackoverflow.com/questions/16706098/how-can-i-emulate-register-globals-in-php-5-4-or-newer

Maar dat leverde geen verbetering.

Gr,

**Comment by physje** [comment]
Impact is laag/nihil.
Als adres geen letter en toevoeging heeft (wat voor de meeste huizen in Nederland zo is), zijn deze variabelen leeg.
Zou inderdaad mooier zijn ze netjes te initialiseren aan het begin van de functie splitStreetAndNumberFromAdress :)

Draai op mijn ontwikkelomgeving (XAMPP) PHP 5.6.30.
Op mijn webserver draait ook PHP 5.6
