### ISSUE TITLE
cron funda/admin/combine_batch.php: access array offset on value of type null en mysqli_num_rows() expects parameter 1 to be mysqli_result

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#16]
Hoi,

Bij runnen cron funda/admin/combine_batch.php krijg ik:

PHP Notice:  Trying to access array offset on value of type null in funda/admin/combine_batch.php on line 32
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 34
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 35
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 38
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 39
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 40
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 41
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 42
PHP Notice:  Trying to access array offset on value of type bool in funda/admin/combine_batch.php on line 43
PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in funda/admin/combine_batch.php on line 48

Vooral het laatste zal wel voor problemen zorgen neem ik aan.

Gr, J

**Comment by physje** [comment]
Zou het kunnen zijn dat de query geen resultaten oplevert (dus geen offline huizen die niet verkocht zijn)?
Die check nu toegevoegd in de code, hopelijk voorkomt dat deze meldingen

**Comment by jalbstmeijer** [comment]
Ik krijg nu idd "Geen offline huizen die niet verkocht zijnGeen werk aan de winkel"

Van mij mag dit issue gesloten worden.

Ik stuu nog even een pull om een break achter de strings te plaatsen
