### ISSUE TITLE
Error bij inserten default Admin account credentials

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#17]
mysql funda < tabel_2020-06-06.sql

ERROR 1364 (HY000) at line 91: Field 'userkey' doesn't have a default value

fix:

INSERT INTO `funda_members` (`id`, `name`, `username`, `password`, `level`, `mail`, `userkey`, `api_token`, `account`, `lastLogin`) VALUES (1, 'Admin', 'admin', '21232f297a57a5a743894a0e4a801fc3', 3, '', '','', 0, 0);

ipv

INSERT INTO `funda_members` (`id`, `name`, `username`, `password`, `level`, `mail`, `account`, `lastLogin`) VALUES (1, 'Admin', 'admin', '21232f297a57a5a743894a0e4a801fc3', 3, '', 0, 0);

**Comment by physje** [comment]
Opgelost met laatste commit ([e2a1e84](https://github.com/physje/funda/commit/e2a1e849bd1621757931f2bdbb347dd23fce6410))
