### ISSUE TITLE
Error bij loggen

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#18]
INSERT INTO funda_log (tijd, type, opdracht, huis, message) VALUES (1625350833, 'info', '0', '', 'Inlogpoging vanaf x.x.x.x')

ERROR 1366 (HY000) at line 1: Incorrect integer value: '' for column 'opdracht' at row 1
ERROR 1366 (HY000) at line 1: Incorrect integer value: '' for column 'huis' at row 1

Volgens tabel_2020-06-06.sql moeten dat inderdaad interger values zijn, quick fix;

auth/interface.php

-toLog('info', '', '', 'Inlogpoging vanaf '. $_SERVER['REMOTE_ADDR']);
+toLog('info', '0', '0', 'Inlogpoging vanaf '. $_SERVER['REMOTE_ADDR']);

**Comment by jalbstmeijer** [comment]
Er zijn meer plekken in de code waar dit fout gaat.

**Comment by physje** [comment]
Opgelost met de laatste commit ([e2a1e84](https://github.com/physje/funda/commit/e2a1e849bd1621757931f2bdbb347dd23fce6410))
