### ISSUE TITLE
Logout redirect niet naar login pagina

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#19]
Bij een default install waarbij site gewoon op / draait, krijg je bij default een blanco pagina bij uitloggen.
Mogelijk is "/" een betere default waarde voor $ScriptURL in include/config_funda.php.

**Comment by physje** [comment]
Opgelost met de laatste commit ([e2a1e84](https://github.com/physje/funda/commit/e2a1e849bd1621757931f2bdbb347dd23fce6410))
