### ISSUE TITLE
Funda check call restulteerd in 401

### ISSUE THREAD

**Issue by jalbstmeijer** [physje/funda#25]
failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized in /var/www/html/include/functions.php on line 110

https://partnerapi.funda.nl/feeds/Aanbod.svc/rss/?type=koop&zo=/amsterdam/

**Comment by physje** [comment]
Is bekend.
funda heeft de partnerapi afgesloten
Staat ook in de README.md
