### ISSUE TITLE
Cannot reach db + MySQL foutmelding

### ISSUE THREAD

**Issue by bahwilson** [physje/funda#4]
Wanneer ik via localhost index.php run dan krijg ik de foutmelding "Cannot reach database".

MySQL meldt: #1364 - Field 'userkey' doens't have a default value.
Dit gebeurt bij het invoeren van een SQL via phpadmin.

Wat doe ik fout?

**Comment by bartn** [comment]
Als je het stukje onder CREATE TABLE funda members (line 150) vervangt door 
`INSERT INTO `funda_members` (`id`, `name`, `username`, `password`, `level`, `mail`, `userkey`, `api_token`, `account`, `lastLogin`) VALUES
(1, 'Admin', 'admin', '21232f297a57a5a743894a0e4a801fc3', 3, '', 0, 0, 0, 0);`
dan wordt je tabel in ieder geval aangemaakt.

**Comment by physje** [comment]
Sorry voor de late reactie, had geen melding gehad van deze issues.

userkey bevat de Pushover-userkey van de gebruiker. Als je pushover niet gebruikt kan je hier volgens mij alles invullen.
De oplossing van bartn werkt waarschijnlijk ook prima.
