### ISSUE TITLE
Missing shared_functions.php?

### ISSUE THREAD

**Issue by pietje63** [physje/funda#5]
I first tested the "regular branch" and experience the same blocks you refer to.

After "installing" the API branch, I get the following error

Warning: include(XXX/include/../../general_include/shared_functions.php): failed to open stream: No such file or directory in XXX/include/config.php on line 188 Warning: include(): Failed opening 'XXX/include/../../general_include/shared_functions.php' for inclusion (include_path='.') in XXX/include/config.php on line 188 Fatal error: Call to undefined function connect_db() in XXX/api2/index.php on line 5 

The first warning (shared_functions) can be manually edited, should this be a reference to "general_functions.php"?
The other errors are related.

After fixing this error, I face another issue (which is more complex to fix). The login check (auth\objects\checklogin_db.php) uses mysqli queries, whereas it refers to "$db" as the database link. $db based on general_functions.php is however a mysql (without i) resource. Therefore I doubt whether a reference to general_functions is correct or not..

**Comment by pietje63** [comment]
fixing 
1) reference to general_functions 
and 
2) changing the connect function in general_functions to mysqli works for most of the scripts.

**Comment by physje** [comment]
Ik heb 2 soorten scripts draaien : aantal oude die nog mysql gebruiken en aantal nieuwe die mysqli gebruiken.
De eerste gebruiken general_functions.php, de tweede shared_functions.php.

Heb kort geleden  () het funda-script overgezet van [mysql naar mysqli](https://github.com/physje/funda/commit/83594157affa8a030455a43151f29f5a792738dd), waarschijnlijk is daar iets niet goed gegaan. Maar verwijzen naar shared_functions.php ipv general_functions.php zou het probleem moeten oplossen.

**Comment by pietje63** [comment]
Dank voor de terugkoppeling, dacht al zoiets. Kan het kloppen dat shared_functions.php ontbreekt in de MOVE_THIS_FOLDER map?

Daarnaast is het denk ik goed om de input af en toe te escapen. In mijn database zitten een aantal straten met een ' (zoals J.H. van 't Hoffweg) waar o.a. edit.php moeite mee heeft.

**Comment by physje** [comment]
Laatste commit bevat het betreffende bestand.

Wat betreft escapen, een pull-request sla ik nooit af ;)
