### ISSUE TITLE
mysqli_num_rows() expects parameter 1 to be mysqli_result

### ISSUE THREAD

**Issue by Mmalherbe** [physje/funda#8]
Allereerst supertof project(je) !

Helaas bij het opstellen van de applicatie ontvang ik een error: 

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /var/www/vhosts/example.com/public_html/funda/check.php on line 34

**Comment by physje** [comment]
check ff of er een wijken-tabel bestaat, lijkt erop dat je die vergeten bent aan te maken.
in "tabel_14-08-2019.sql" ontbreekt die nog, daarom wordt die in "onderhoud/onderhoud_2019-11-25.php" aangemaakt
