### ISSUE TITLE
Warning: mysqli_insert_id() expects exactly 1 parameter, 0 given 

### ISSUE THREAD

**Issue by Mmalherbe** [physje/funda#9]
Nog eentje :), niet zeker of het komt doordat je hem hebt moeten aanpassen naar RSSfeeds.

Deze komt te voorschijn bij het toevoegen van een nieuwe opdracht en dan 1 tijdstip ( om de x uur) aan te drukken. 

Warning: mysqli_insert_id() expects exactly 1 parameter, 0 given in /var/www/vhosts/example.com/public_html/funda/admin/edit_opdrachten.php on line 43

**Comment by physje** [comment]
Kan het niet reproduceren.
Wat is de exacte sql-query waar hij op hangt? Zit daar een gek leesteken oid in?

**Comment by jalbstmeijer** [comment]
Soort gelijke issues als ik de funda check run;

[Sat Jun 06 16:08:37.457409 2020] [:error] [pid 3996] [client xxx:41692] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /xxx/funda/check.php on line 34, referer: xxx/funda/index.php

[Sat Jun 06 16:08:37.457438 2020] [:error] [pid 3996] [client xxx:41692] PHP Warning:  Division by zero in /xxx/funda/check.php on line 37, referer: http://xxx/funda/index.php

[Sat Jun 06 16:08:37.457714 2020] [:error] [pid 3996] [client xxx:41692] PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /xxx/funda/include/functions.php on line 2171, referer: http://xxx/funda/index.php

**Comment by physje** [comment]
Gezien de regelnummer denk ik dat je tabel met straten en wijken leeg is.
Dat zou in theorie alleen voor mogen komen als er nog geen huizen gevonden zijn.
Moet even denken over een nette oplossing.

Voor nu zijn er aantal oplossingen mogelijk
1. Probeer eens via http://xxx/funda/admin/edit_opdrachten.php een opdracht te runnen.
2. Probeer eens http://xxx/funda/check.php op het hele uur of 1 minuut daarna te runnen
3. Pas de code in check.php aan, door bv regel 25 t/m 58 te verwijderen

**Comment by physje** [comment]
Ontdek dat de tabel voor wijken niet is opgenomen in het overzicht van tabellen.

```
CREATE TABLE `funda_wijken` (
  `id` int(6) NOT NULL,
  `active` set('0','1') NOT NULL DEFAULT '1',
  `naam_leesbaar` text NOT NULL,
  `naam_funda` text NOT NULL,
  `stad` text NOT NULL,
  `last_checked` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Hopelijk lost dat het probleem op.

**Comment by jalbstmeijer** [comment]
Met deze table, krijg ik de error idd niet meer, bedankt!
